name: CI Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./:./dags
      # Tell your code it's in a test environment
      ENV: test 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     # Ensure requirements.txt includes pysqlite3-binary
      #     pip install -r requirements.txt
      #     pip install pytest unittest-xml-reporting

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use the same constraint file as the Dockerfile
          pip install -r requirements.txt --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt"
          pip install pytest unittest-xml-reporting
      
      - name: Run Pytest
        env:
          CHROMA_DB_PATH: ./test_chroma_db
          ENV: test
        run: pytest tests/tax_assistant_pytest.py

      - name: Run Unittests
        env:
          CHROMA_DB_PATH: ./test_chroma_db
        run: python -m unittest discover -s tests -p "tax_assistant_unittest.py"